### ISSUE TITLE
What is this for, exactly?

### ISSUE THREAD

**Issue by tomgs** [FedericoPonzi/Horust#34]
@FedericoPonzi While the general concept of an init system is clear to most everyone who's ever dealt with a *NIX system, I'm not exactly sure whether a **container** init system is something most people spend time thinking about.

To be clearer - why do I need `systemd` inside a container? Don't containers already have `systemd`? Is Horust a replacement for `systemd`, even? How does it stack up against other tools? Can it replace something I have in my stack now, even in its alpha phase?

I'm not saying that Horust _should_ be anything re the above, I'm saying that outside of the immediate people who you and I talked to about the project, it's unclear exactly what it's doing here and what it... well, is.

Let's dream for a sec: If Horust gets big, what would it like? Who would use it? What would it replace?

**Comment by FedericoPonzi** [comment]
The initial idea behind Horust was to create a new and powerful service manager. You give it a bunch of programs to run, some dependencies and constraints, and Horust will make sure to enforce the given configurations.

The init "addition" is just a requirement for being able to run horust inside a container.

> @FedericoPonzi While the general concept of an init system is clear to most everyone who's ever dealt with a *NIX system, I'm not exactly sure whether a **container** init system is something most people spend time thinking about.

Of course not. By design a well thoroughly designed container should run just one binary. But sometimes, you really need to be able to run multiple things inside the same container. There is even a page on [Docker docs](https://docs.docker.com/config/containers/multi-service_container/) for that:

> The container’s main process is responsible for managing all processes that it starts. In some cases, the main process isn’t well-designed, and doesn’t handle “reaping” (stopping) child processes gracefully when the container exits. If your process falls into this category, you can use the --init option when you run the container. The --init flag inserts a tiny init-process into the container as the main process, and handles reaping of all processes when the container exits. 

Docker itself is shipped with tinyinit, which is very useful as a basic init system for most programs. I've seen people ending up with a bash script as a starter script, in which they first spawn a process B as a background job using & and after that the bash script will exec on process A.
See an example [here](https://github.com/reacherhq/backend/blob/6fd5215285cf6b841d8c843857f9b9bf11940c82/scripts/docker_entrypoint.sh).
This approach is fine and with `--init` should work fine. But what happens if B fails and you want to restart it? You would need to start writing some service manager, or use [supervisord](supervisord.org/) (which most people end up with). With supervisord, which today is a 10+ years old piece of software (so I assume very stable at this point), you will need to bring in your container the python runtime, making your container even bigger. Also, some dependencies are hard to express in Supervisord (IMO).
And for serious / production usage you probably want/need one some way to be sure that your service is running. The healthchecker, it's very useful if you want to be sure that your service is running && running properly.


> To be clearer - why do I need `systemd` inside a container? Don't containers already have `systemd`? 

I should have answered the first question. For the second one, the answer is of course not. Few companies have taken the effort of trying to run systemd inside a container - but for what I've read its use is usually discouraged inside containers because of its use of low-level kernel features. So unless you're already very familiar with systemd or you _really_ need it for reasons, it's probably not worth the effort.

> Is Horust a replacement for `systemd`, even? 

I would say yes, because the problem they aim to solve is overlapping. The first use case I had in mind is for containers, because I don't have the presumption that anyone will realistically use it as their own init system in the near future. For this, one would probably need the support by some Linux distro, and someone should writing some mechanism to port systemd services to Horust services and so on. So the first supported use case would be running it inside containers. In the future, the idea would be to create a viable replacement for systemd.

> How does it stack up against other tools? Can it replace something I have in my stack now, even in its alpha phase?

Sure, you can probably replace whatever you're using to run multiple things inside a container (supervisord, s6 and so on) with horust. Also, Horust it's runnable even outside a container as a normal user program. So if you need to run multiple things in a complex workflow, you can give it a try!

 
> I'm not saying that Horust _should_ be anything re the above, I'm saying that outside of the immediate people who you and I talked to about the project, it's unclear exactly what it's doing here and what it... well, is.
> 
> Let's dream for a sec: If Horust gets big, what would it like? Who would use it? What would it replace?

In the far far far far future, I think it could be used as an init system and replace systemd. Using some feature flags, it could be compiled in a more "basic version" which could still be used to run in containers. My best wish would be to keep the code so easy that one dev could just come in, scan through the code and remove all the unneeded feature.
