### ISSUE TITLE
Allow using current directory as config root

### ISSUE THREAD

**Issue by esavier** [FedericoPonzi/Horust#47]
I would like to use horust as development tool. That means, for example, attaching a bunch of horust configs inside the repo, and instead of meddling with docker, use horust to start and manage several applications that would work in tandem.

  * How the feature should work.
i would love to have flag, specifying current directory as a directory to search for config files, i.e.
given following structure in, for example /home/user/apps
`
   bin/service1
   bin/service2
   cfg/service1.toml
   cfg/service2.toml
`
i would like to be able to do something like `horust --here` to start horust  (hopefuly nondemonized) instance to start and run application configured by horust's cfg/*toml configs. Console output would be horust log, while application outputs would follow the rules inside configs

use case would be, for example, testing a bunch of services or applications that have to work together.
Part of the horust that manages the applications and keeps them under supervision would be great for that purpose.

**Comment by FedericoPonzi** [comment]
Hey Mateusz, I'm wondering if horust --services-path would be of help here:
```
        --services-path <services-path>    Path to the directory containing the services [default: /etc/horust/services]
```
Since your config files are inside the cfg directory, I think using `horust --services-path cfg` should be enough to make it work. This is obivously not exactly matching what you had in mind: it's not searching recursively for config files. But would work well with the example you provided, so I'm wondering if this is what you were looking for.

**Comment by esavier** [comment]
Actually i tested it through the weekend and it seems to be working almost as i want it to. Thanks, i think that closes the issue!
Great project btw, many kudos :100:
